// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdfnseoyrcnwiaqmejrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZm5zZW95cmNud2lhcW1lanJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMTAyMzcsImV4cCI6MjA2MzY4NjIzN30.EUk03nxOKIttgnCY3SFFHHtw-XUEM-Do-ulzZJbUgPg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);